apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: django
        tier: frontend
    spec:
      containers:
      - name: django
        image: gcr.io/django-172117/djangodocker:latest
        env:
          # - name: DJANGO_DB_HOST
          #   value: postgres
          # - name: DJANGO_DB_PORT
          #   value: "3306"
          # - name: DJANGO_DB_NAME
          #   value: django
          # - name: DJANGO_DB_USER
          #   value: django
          - name: DJANGO_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
