apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  backend:
    serviceName: nginx
    servicePort: 80
  rules:
    - http:
        paths:
        - path: /hello
          backend:
            serviceName: django
            servicePort: 80
